server:
  port: 8080
spring:
  application:
    name: spring-rest-security
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/cybertek
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: create
    show-sql: true
security:
  jwt:
    secret-key: cybertek










