import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.MethodName.class)
class CalculatorTest {
    //For Unit testing here, generated by IntelliJ-Junit5
    @BeforeEach
    void setupEach(){
        System.out.println("BeforeEach executed!!!");
    }

    @BeforeAll
    public static void setupAll(){
        System.out.println("BeforeAll executed!!!");
    }
    @AfterEach
    void tearEach(){
        System.out.println("AfterEach executed!");
    }
    @AfterAll
    static void tearAll(){
        System.out.println("AfterAll executed!");
    }
    @Test
    void testCase1(){
        System.out.println("this is test case 1!");
        assertEquals(20, 20);
    }
    @Test
    void testCase2(){
        System.out.println("this is test case 2!");

        assertTrue(Calculator.operator.endsWith("add"));
    }
    @Test
    void testCase3(){
        System.out.println("this is test case 3!");

        assertArrayEquals(new int[]{1,2,3}, new int[]{1,2,3}, "Array Equal Test");
    }
    @Test
    void testCase4(){
        System.out.println("this is test case 4!");

        String nullString = null;
        String notNullString="Cybertek:";
        assertNotNull(notNullString, "Null test");
//        assertNotNull(nullString, "Null test");
        assertNull(nullString, "Null testing");
    }

    @Test
    void testCase5(){
        System.out.println("this is test case 5!");

        Calculator c1 = new Calculator();
        Calculator c2 = c1;
        Calculator c3 = new Calculator();

        assertNotSame(c1, c3, "Calculator objects compare");
//        assertNotSame(c1, c2, "Calculator objects compare");
        assertSame(c1, c2, "Calculator objects compare");


    }


    @Test
    void add() {
        int actual = Calculator.add(2,3);
        assertEquals(5, actual);
    }
}