import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class CalculatorTest {
    //For Unit testing here, generated by IntelliJ-Junit5

    @Test
    void testCase1(){
        assertEquals(20, 20);
    }
    @Test
    void testCase2(){
        assertTrue(Calculator.operator.endsWith("add"));
    }
    @Test
    void testCase3(){
        fail("not implemented yet");
    }
    @Test
    void add() {
        int actual = Calculator.add(2,3);
        assertEquals(5, actual);
    }
}